CREATE TABLE vending_machine (
    machine_id text PRIMARY KEY,
    version bigint NOT NULL DEFAULT 0,
    CONSTRAINT ck_vending_machine_id_not_blank CHECK (btrim(machine_id) <> ''),
    CONSTRAINT ck_vending_machine_version_non_negative CHECK (version >= 0)
);

CREATE TABLE machine_slot (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    machine_id text NOT NULL REFERENCES vending_machine (machine_id) ON DELETE CASCADE,
    slot_code text NOT NULL,
    product_id text NOT NULL,
    product_name text NOT NULL,
    price_amount bigint NOT NULL,
    price_currency varchar(16) NOT NULL,
    quantity integer NOT NULL,
    CONSTRAINT uq_machine_slot_machine_code UNIQUE (machine_id, slot_code),
    CONSTRAINT ck_machine_slot_code_not_blank CHECK (btrim(slot_code) <> ''),
    CONSTRAINT ck_machine_slot_product_id_not_blank CHECK (btrim(product_id) <> ''),
    CONSTRAINT ck_machine_slot_product_name_not_blank CHECK (btrim(product_name) <> ''),
    CONSTRAINT ck_machine_slot_price_positive CHECK (price_amount > 0),
    CONSTRAINT ck_machine_slot_price_currency CHECK (price_currency = 'UNIT'),
    CONSTRAINT ck_machine_slot_quantity_non_negative CHECK (quantity >= 0)
);

CREATE TABLE cash_inventory (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    machine_id text NOT NULL REFERENCES vending_machine (machine_id) ON DELETE CASCADE,
    denomination smallint NOT NULL,
    quantity integer NOT NULL,
    CONSTRAINT uq_cash_inventory_machine_denomination UNIQUE (machine_id, denomination),
    CONSTRAINT ck_cash_inventory_denomination CHECK (denomination IN (5, 10, 20, 50)),
    CONSTRAINT ck_cash_inventory_quantity_non_negative CHECK (quantity >= 0)
);

CREATE TABLE purchase_session (
    session_id text PRIMARY KEY,
    machine_id text NOT NULL REFERENCES vending_machine (machine_id) ON DELETE CASCADE,
    status varchar(16) NOT NULL,
    started_at timestamp with time zone NOT NULL,
    last_activity_at timestamp with time zone NOT NULL,
    CONSTRAINT ck_purchase_session_id_not_blank CHECK (btrim(session_id) <> ''),
    CONSTRAINT ck_purchase_session_status
        CHECK (status IN ('ACTIVE', 'COMPLETED', 'REFUNDED', 'EXPIRED'))
);

CREATE UNIQUE INDEX uq_purchase_session_one_active_per_machine
    ON purchase_session (machine_id)
    WHERE status = 'ACTIVE';

CREATE TABLE session_tender (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id text NOT NULL REFERENCES purchase_session (session_id) ON DELETE CASCADE,
    denomination smallint NOT NULL,
    quantity integer NOT NULL,
    CONSTRAINT uq_session_tender_session_denomination UNIQUE (session_id, denomination),
    CONSTRAINT ck_session_tender_denomination CHECK (denomination IN (5, 10, 20, 50)),
    CONSTRAINT ck_session_tender_quantity_non_negative CHECK (quantity >= 0)
);
